// lifecycle.go — Scenario F + F2: graceful shutdown (wire variant).
//
// wire has NO lifecycle management — this is identical to 01-manual.
// wire only generates constructor wiring; shutdown is always manual.
//
// Key point: wire and manual are indistinguishable for lifecycle concerns.
// The only difference between 01-manual and 03-wire is how constructors
// are called (written by hand vs generated by tool). Once the app is running,
// they behave identically.
package main

import (
	"context"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/labstack/echo/v4"
)

type temporalWorkerStopper interface{ Stop() }
type k8sClientCloser interface{ Close() }

type noopTemporalWorker struct{}

func (n *noopTemporalWorker) Stop() { slog.Info("temporal worker stopped") }

type noopK8sClient struct{}

func (n *noopK8sClient) Close() { slog.Info("k8s client closed") }

// runWithOrderedShutdown — identical to 01-manual/lifecycle.go.
// wire adds nothing to lifecycle management.
func runWithOrderedShutdown(e *echo.Echo, temporal temporalWorkerStopper, k8s k8sClientCloser, port string) {
	go func() {
		slog.Info("http server starting", "port", port)
		if err := e.Start(":" + port); err != nil && err != http.ErrServerClosed {
			slog.Error("http server error", "error", err)
			os.Exit(1)
		}
	}()

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	<-ctx.Done()

	slog.Info("shutdown signal received — draining in order")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := e.Shutdown(shutdownCtx); err != nil {
		slog.Error("http shutdown error", "error", err)
	}
	slog.Info("http stopped")

	temporal.Stop()
	k8s.Close()

	slog.Info("shutdown complete")
}
