// 03-wire: Dependency injection via google/wire — code generation.
//
// ── SCENARIO A — Initial wiring (2 feature slices: compute + database) ────
// Wiring lines in wire.go wire.Build(): 8 entries  [marked with WIRE]
// Files involved in wiring: wire.go (spec) + wire_gen.go (generated, never edit)
// Error detection: wire generate time (before compile)
//
// ── SCENARIO B — Add 1 new feature slice (storage) ────────────────────────
// New files: internal/storage/service.go, internal/storage/handler.go
// Changes in wire.go:
//   + storage.NewService entry   [+1 line]
//   + storage.NewHandler entry   [+1 line]
// Then: wire ./cmd/api-server/ → regenerates wire_gen.go
// Changes in this file:
//   + *storage.Handler field in handlers struct   [+1 line]
//   + storageH arg in newHandlers()               [+1 line]
//   + delegation methods for storage endpoints    [+N lines]
// Total delta: ~3 lines in wire.go, ~3 lines in main.go + delegation methods
//
// ── ERROR DETECTION ────────────────────────────────────────────────────────
// Remove platform.NewTemporalClient from wire.Build → wire generate fails:
//   "wire: cannot find provider for shared.TemporalClient"
// Caught before compilation — earlier than fx (which fails at app.Run())
// but still requires a separate generate step unlike manual (pure compile).
//
// ── RUNTIME DEPENDENCY FOOTPRINT ──────────────────────────────────────────
// wire is a BUILD TOOL ONLY — it does not ship in your binary.
// The generated wire_gen.go contains only plain Go constructor calls.
// Runtime dependency added: 0 (wire is a dev tool, not a runtime import)
// This is fundamentally different from uber/fx which is a runtime dependency.
//
// ── AI ASSISTANCE ──────────────────────────────────────────────────────────
// AI must know:
// 1. The wireinject build tag and wire.Build() convention in wire.go
// 2. That wire_gen.go is generated — never edit it manually
// 3. To run `wire` after adding new providers
// The wire.go file is readable and the graph is explicit (like manual).
// Risk: AI may edit wire_gen.go directly instead of regenerating — wrong.
//
// ── NOTE: MAINTENANCE STATUS ──────────────────────────────────────────────
// google/wire has been in maintenance mode since ~2022. No active development.
// The tool works and is stable, but new features will not be added.
// See: https://github.com/google/wire/issues/637
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	api "github.com/kitchen-sink/03-wire/gen"
	"github.com/kitchen-sink/03-wire/internal/compute"
	"github.com/kitchen-sink/03-wire/internal/database"
	"github.com/kitchen-sink/di-shared"
)

// ── Handlers ──────────────────────────────────────────────────────────────

type handlers struct {
	compute  *compute.Handler
	database *database.Handler
}

func newHandlers(c *compute.Handler, d *database.Handler) *handlers {
	return &handlers{compute: c, database: d}
}

var _ api.StrictServerInterface = (*handlers)(nil)

func (h *handlers) CreateCompute(ctx context.Context, req api.CreateComputeRequestObject) (api.CreateComputeResponseObject, error) {
	return h.compute.CreateCompute(ctx, req)
}
func (h *handlers) GetCompute(ctx context.Context, req api.GetComputeRequestObject) (api.GetComputeResponseObject, error) {
	return h.compute.GetCompute(ctx, req)
}
func (h *handlers) CreateDatabase(ctx context.Context, req api.CreateDatabaseRequestObject) (api.CreateDatabaseResponseObject, error) {
	return h.database.CreateDatabase(ctx, req)
}
func (h *handlers) GetDatabase(ctx context.Context, req api.GetDatabaseRequestObject) (api.GetDatabaseResponseObject, error) {
	return h.database.GetDatabase(ctx, req)
}

// ── Server setup ──────────────────────────────────────────────────────────

func main() {
	// initializeHandlers() is generated by wire in wire_gen.go.
	// It contains the same plain Go constructor calls as 01-manual/buildApp()
	// but written by the tool, not by hand.
	app, err := initializeHandlers()
	if err != nil {
		slog.Error("failed to initialize", "error", err)
		return
	}

	e := echo.New()
	e.HideBanner = true
	e.Use(middleware.RequestIDWithConfig(middleware.RequestIDConfig{
		Generator: func() string { return uuid.New().String() },
	}))

	e.HTTPErrorHandler = func(err error, c echo.Context) {
		reqID := c.Response().Header().Get(echo.HeaderXRequestID)
		var de *shared.DomainError
		if errors.As(err, &de) {
			if de.Cause != nil {
				slog.Error("domain error", "code", de.Code, "cause", de.Cause, "request_id", reqID)
			}
			c.JSON(de.Status, map[string]string{"code": de.Code, "message": de.Message, "requestId": reqID})
			return
		}
		var he *echo.HTTPError
		if errors.As(err, &he) {
			c.JSON(he.Code, map[string]string{"code": "HTTP_ERROR", "message": http.StatusText(he.Code), "requestId": reqID})
			return
		}
		slog.Error("unhandled error", "error", err, "request_id", reqID)
		c.JSON(500, map[string]string{"code": "INTERNAL_ERROR", "message": "an internal error occurred", "requestId": reqID})
	}

	api.RegisterHandlers(e, api.NewStrictHandler(app, nil))

	slog.Info("03-wire listening", "port", 8083)
	e.Logger.Fatal(e.Start(":8083"))
}
