// 04-chi-strict: chi + oapi-codegen strict mode.
//
// KEY OBSERVATION — the global error handler problem with chi + strict mode:
//
// The chi strict wrapper generated by oapi-codegen handles returned errors INLINE:
//
//   func (sh *strictHandler) CreateCompute(w http.ResponseWriter, r *http.Request) {
//       resp, err := sh.ssi.CreateCompute(r.Context(), request)
//       if err != nil {
//           sh.options.ResponseErrorHandlerFunc(w, r, err)  // ← writes response HERE
//           return
//       }
//       ...
//   }
//
// To get consistent error responses you MUST set ResponseErrorHandlerFunc in options.
// This works but is extra wiring that echo doesn't require —
// echo's strict wrapper returns the error to the framework, which routes to HTTPErrorHandler.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"

	"github.com/go-chi/chi/v5"
	chimiddleware "github.com/go-chi/chi/v5/middleware"

	api "github.com/kitchen-sink/04-chi-strict/gen"
	"github.com/kitchen-sink/shared"
)

var _ api.StrictServerInterface = (*Handlers)(nil)

type Handlers struct{ store *shared.Store }

type ErrorResponse struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId,omitempty"`
}

func toStatus(s string) api.ComputeInstanceStatus {
	return api.ComputeInstanceStatus(s)
}

func errorHandlerFunc(w http.ResponseWriter, r *http.Request, err error) {
	reqID := chimiddleware.GetReqID(r.Context())
	w.Header().Set("Content-Type", "application/json")
	var de *shared.DomainError
	if errors.As(err, &de) {
		if de.Cause != nil {
			slog.Error("domain error", "code", de.Code, "cause", de.Cause, "request_id", reqID)
		}
		w.WriteHeader(de.Status)
		json.NewEncoder(w).Encode(ErrorResponse{Code: de.Code, Message: de.Message, RequestID: reqID})
		return
	}
	slog.Error("unhandled error", "error", err, "request_id", reqID)
	w.WriteHeader(500)
	json.NewEncoder(w).Encode(ErrorResponse{Code: "INTERNAL_ERROR", Message: "an internal error occurred", RequestID: reqID})
}

func (h *Handlers) CreateCompute(ctx context.Context, req api.CreateComputeRequestObject) (api.CreateComputeResponseObject, error) {
	body := req.Body
	if body.Name == "" {
		return nil, &shared.DomainError{Code: "INVALID_REQUEST", Message: "name is required", Status: 400}
	}
	size := "medium"
	if body.Size != nil {
		size = string(*body.Size)
	}
	inst, err := h.store.Create(body.Name, body.TenantId, string(body.Provider), size)
	if err != nil {
		return nil, err
	}
	wfID, status, msg := inst.WorkflowID, "provisioning", "compute instance provisioning started"
	return api.CreateCompute202JSONResponse{WorkflowId: &wfID, Status: &status, Message: &msg}, nil
}

func (h *Handlers) ListCompute(ctx context.Context, req api.ListComputeRequestObject) (api.ListComputeResponseObject, error) {
	limit := 20
	if req.Params.Limit != nil {
		limit = *req.Params.Limit
	}
	instances, err := h.store.List(req.Params.TenantId, limit)
	if err != nil {
		return nil, err
	}
	items := make([]api.ComputeInstance, 0, len(instances))
	for _, inst := range instances {
		name, tenantID, provider, size, status, wfID :=
			inst.Name, inst.TenantID, inst.Provider, inst.Size, toStatus(inst.Status), inst.WorkflowID
		items = append(items, api.ComputeInstance{Name: &name, TenantId: &tenantID, Provider: &provider, Size: &size, Status: &status, WorkflowId: &wfID})
	}
	total := len(items)
	return api.ListCompute200JSONResponse{Items: &items, Total: &total}, nil
}

func (h *Handlers) GetCompute(ctx context.Context, req api.GetComputeRequestObject) (api.GetComputeResponseObject, error) {
	inst, err := h.store.Get(req.Name)
	if err != nil {
		return nil, err
	}
	name, tenantID, provider, size, status, wfID :=
		inst.Name, inst.TenantID, inst.Provider, inst.Size, toStatus(inst.Status), inst.WorkflowID
	return api.GetCompute200JSONResponse{Name: &name, TenantId: &tenantID, Provider: &provider, Size: &size, Status: &status, WorkflowId: &wfID}, nil
}

func (h *Handlers) DeleteCompute(ctx context.Context, req api.DeleteComputeRequestObject) (api.DeleteComputeResponseObject, error) {
	if err := h.store.Delete(req.Name); err != nil {
		return nil, err
	}
	return api.DeleteCompute204Response{}, nil
}

func main() {
	store := shared.NewStore()
	r := chi.NewRouter()
	r.Use(chimiddleware.RequestID)

	opts := api.StrictHTTPServerOptions{
		ResponseErrorHandlerFunc: errorHandlerFunc,
	}
	api.HandlerFromMux(api.NewStrictHandlerWithOptions(&Handlers{store: store}, nil, opts), r)

	slog.Info("04-chi-strict listening", "port", 9004)
	http.ListenAndServe(":9004", r)
}
