// 02-echo-strict: Echo + oapi-codegen strict mode.
//
// Key things to observe vs 01-echo-standard:
// - StrictServerInterface: compiler enforces ALL endpoints are implemented
//   (add an endpoint to the spec, forget to implement it → build fails)
// - No manual json.Decode, no manual required-field checks — generated by codegen
// - Handler returns (ResponseObject, error) — never writes to http.ResponseWriter directly
// - Errors returned from handlers flow to e.HTTPErrorHandler automatically
// - Global error handler works perfectly with strict mode — that's the echo advantage
//
// vs 04-chi-strict:
// - Chi's generated strict wrapper catches returned errors INLINE and writes its own
//   response before HTTPErrorHandler can intercept — global handler is bypassed
// - Echo's generated strict wrapper returns the error to the framework instead
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	api "github.com/kitchen-sink/02-echo-strict/gen"
	"github.com/kitchen-sink/shared"
)

var _ api.StrictServerInterface = (*Handlers)(nil)

type Handlers struct{ store *shared.Store }

type ErrorResponse struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId,omitempty"`
}

func toStatus(s string) api.ComputeInstanceStatus {
	return api.ComputeInstanceStatus(s)
}

func (h *Handlers) CreateCompute(ctx context.Context, req api.CreateComputeRequestObject) (api.CreateComputeResponseObject, error) {
	body := req.Body
	if body.Name == "" {
		return nil, &shared.DomainError{Code: "INVALID_REQUEST", Message: "name is required", Status: 400}
	}
	size := "medium"
	if body.Size != nil {
		size = string(*body.Size)
	}
	inst, err := h.store.Create(body.Name, body.TenantId, string(body.Provider), size)
	if err != nil {
		return nil, err
	}
	wfID, status, msg := inst.WorkflowID, "provisioning", "compute instance provisioning started"
	return api.CreateCompute202JSONResponse{WorkflowId: &wfID, Status: &status, Message: &msg}, nil
}

func (h *Handlers) ListCompute(ctx context.Context, req api.ListComputeRequestObject) (api.ListComputeResponseObject, error) {
	limit := 20
	if req.Params.Limit != nil {
		limit = *req.Params.Limit
	}
	instances, err := h.store.List(req.Params.TenantId, limit)
	if err != nil {
		return nil, err
	}
	items := make([]api.ComputeInstance, 0, len(instances))
	for _, inst := range instances {
		name, tenantID, provider, size, status, wfID :=
			inst.Name, inst.TenantID, inst.Provider, inst.Size, toStatus(inst.Status), inst.WorkflowID
		items = append(items, api.ComputeInstance{Name: &name, TenantId: &tenantID, Provider: &provider, Size: &size, Status: &status, WorkflowId: &wfID})
	}
	total := len(items)
	return api.ListCompute200JSONResponse{Items: &items, Total: &total}, nil
}

func (h *Handlers) GetCompute(ctx context.Context, req api.GetComputeRequestObject) (api.GetComputeResponseObject, error) {
	inst, err := h.store.Get(req.Name)
	if err != nil {
		return nil, err
	}
	name, tenantID, provider, size, status, wfID :=
		inst.Name, inst.TenantID, inst.Provider, inst.Size, toStatus(inst.Status), inst.WorkflowID
	return api.GetCompute200JSONResponse{Name: &name, TenantId: &tenantID, Provider: &provider, Size: &size, Status: &status, WorkflowId: &wfID}, nil
}

func (h *Handlers) DeleteCompute(ctx context.Context, req api.DeleteComputeRequestObject) (api.DeleteComputeResponseObject, error) {
	if err := h.store.Delete(req.Name); err != nil {
		return nil, err
	}
	return api.DeleteCompute204Response{}, nil
}

func main() {
	store := shared.NewStore()
	e := echo.New()
	e.HideBanner = true
	e.Use(middleware.RequestIDWithConfig(middleware.RequestIDConfig{
		Generator: func() string { return uuid.New().String() },
	}))

	e.HTTPErrorHandler = func(err error, c echo.Context) {
		reqID := c.Response().Header().Get(echo.HeaderXRequestID)
		var de *shared.DomainError
		if errors.As(err, &de) {
			if de.Cause != nil {
				slog.Error("domain error", "code", de.Code, "cause", de.Cause, "request_id", reqID)
			}
			c.JSON(de.Status, ErrorResponse{Code: de.Code, Message: de.Message, RequestID: reqID})
			return
		}
		var he *echo.HTTPError
		if errors.As(err, &he) {
			c.JSON(he.Code, ErrorResponse{Code: "HTTP_ERROR", Message: http.StatusText(he.Code), RequestID: reqID})
			return
		}
		slog.Error("unhandled error", "error", err, "request_id", reqID)
		c.JSON(500, ErrorResponse{Code: "INTERNAL_ERROR", Message: "an internal error occurred", RequestID: reqID})
	}

	api.RegisterHandlers(e, api.NewStrictHandler(&Handlers{store: store}, nil))
	slog.Info("02-echo-strict listening", "port", 9002)
	e.Logger.Fatal(e.Start(":9002"))
}
